["$globals"]
vars = [
    {"pytest_args" = "-vv"},
    {"pytest_path" = "tests/"},
    {"run" = "poetry run"},
    {"poetry_extra" = ""},
]

[all]
alias = "install"

[install]
phony = true
keep_ts = true
requires = ["requirements.txt"]
commands = [
    "poetry install ${poetry_extra}",
]

[format]
phony = true
requires = ["install"]
commands = [
    "${run} isort .",
    "${run} black .",
]

[lint]
phony = true
requires = ["install"]
commands = [
    "${run} flake8 .",
    "${run} isort --check .",
    "${run} black --check .",
]

[tests]
phony = true
requires = ["install"]
commands = [
    "${run} pytest ${pytest_args} ${pytest_path}",
]

["poetry.lock"]
requires = ["pyproject.toml"]
commands = [
    "poetry lock && touch ${.target}",
]

["requirements.txt"]
requires = ["poetry.lock"]
commands = [
    "poetry export --without-hashes -f requirements.txt -o ${.target}",
]
